module.exports = [
    { path : '.', data : [{ test : 'test' }], res : [{ test : 'test' }]},
    { path : '.', data : 'test', res : ['test']},
    { path : '.', data : 5, res : [5]},
    { path : '.', data : true, res : [true]},
    { path : '.', data : [], res : []},
    { path : '.data', data : { data : []}, res : []},
    { path : '.data', data : [{ data : []}], res : []},
    { path : '.data', data : [{ data : [1]}], res : [1]},
    { path : '.name', res : ['books and authors']},
    { path : '.noexists', res : []},
    { path : '."test.test"', data : { 'test.test' : 'test' }, res : ['test']},
    { path : '.authors.name', res : ['Nicholas C. Zakas', 'Douglas Crockford', 'Robert C. Martin', 'John Resig']},
    { path : '.books.author.name', res : ['Robert C. Martin', 'Nicholas C. Zakas', 'Robert C. Martin', 'Douglas Crockford', 'Douglas Crockford']},
    { path : '.info.*', res : ['books about javascript', 'content']},
    { path : '.data', data : [{ data : [1, 2]}, { data : 3}, { data : [4, 5] }, { data : 6 }], res : [1, 2, 3, 4, 5, 6]},
    { path : '.*', data : [{ data : [1, 2]}, { data : 3}, { data : [4, 5] }, { data : 6 }], res : [1, 2, 3, 4, 5, 6]},
    { path : '.data.*', data : [{ data : [1, 2]}, { data : [[3, 4]]}, { data : [[[5, 6]]] }], res : [3, 4, [5, 6]]},
    { path : '.data.*.*', data : [{ data : [1, 2]}, { data : [[3, 4]]}, { data : [[[5, 6]]] }], res : [5, 6]},
    { path : '.data.*', data : { data : 'string' }, res : []}
];
